#ifndef REQUEST_ENUM_H
#define REQUEST_ENUM_H

enum RequestEnum
{
    HOUSE_REQUEST = 0,
    HOUSE_REQUEST_ACK,
    ENTER_HOME,
    HOME_FREE,
    FENCE_REQUEST,
    FENCE_REQUEST_ACK,
    FENCE_FREE,
    ENTER_FENCE
};

#endif